#include "openfhe.h"
#include <complex>
#include <vector>
#include <cstdio>
using namespace lbcrypto; using C=std::complex<double>; using CT=Ciphertext<DCRTPoly>;
static DCRTPoly make_inv2(const std::shared_ptr<ILDCRTParams<BigInteger>>& ep){DCRTPoly out(ep,Format::COEFFICIENT,true);for(size_t j=0;j<ep->GetParams().size();++j){NativePoly t(ep->GetParams()[j],Format::COEFFICIENT,true);t[0]=NativeInteger(2).ModInverse(ep->GetParams()[j]->GetModulus());out.SetElementAtIndex(j,t);}out.SetFormat(Format::EVALUATION);return out;}
static void inv2(CT&ct){auto inv=make_inv2(ct->GetElements()[0].GetParams());for(auto&c:ct->GetElements())c*=inv;}
static void times2(CT&ct){for(auto&c:ct->GetElements()){c.SetFormat(Format::COEFFICIENT);c=c.Times(2);c.SetFormat(Format::EVALUATION);}}
static void show(const CryptoContext<DCRTPoly>&cc,const CT&ct,const PrivateKey<DCRTPoly>&sk,const char*n){Plaintext p;cc->Decrypt(ct,sk,&p);p->SetLength(2);auto v=p->GetCKKSPackedValue();printf("%s level=%zu scale=%.6e noiseDeg=%zu [%.8g%+.8gi, %.8g%+.8gi]\n",n,ct->GetLevel(),ct->GetScalingFactor(),ct->GetNoiseScaleDeg(),v[0].real(),v[0].imag(),v[1].real(),v[1].imag());}
int main(){CCParams<CryptoContextCKKSRNS>p;p.SetMultiplicativeDepth(8);p.SetScalingModSize(59);p.SetRingDim(1<<16);p.SetSecurityLevel(HEStd_128_classic);p.SetScalingTechnique(FIXEDMANUAL);p.SetCKKSDataType(COMPLEX);auto cc=GenCryptoContext(p);for(auto f:{PKE,KEYSWITCH,LEVELEDSHE,ADVANCEDSHE})cc->Enable(f);auto kp=cc->KeyGen();uint32_t cj=2*cc->GetRingDimension()-1;auto ck=cc->EvalAutomorphismKeyGen(kp.secretKey,{cj});std::vector<C>x(cc->GetRingDimension()/2);x[0]=C(.1,.2);x[1]=C(.3,.4);auto ct=cc->Encrypt(kp.publicKey,cc->MakeCKKSPackedPlaintext(x));auto poly=ct->GetElements()[0];poly.SetFormat(Format::EVALUATION);auto invpoly=make_inv2(poly.GetParams());auto round=poly*invpoly;round*=NativeInteger(2);bool same=true;for(size_t j=0;j<poly.GetAllElements().size();++j)for(size_t k=0;k<poly.GetAllElements()[j].GetLength();++k)if(poly.GetAllElements()[j][k]!=round.GetAllElements()[j][k]){same=false;break;}printf("dcrt_roundtrip=%s\\n",same?"PASS":"FAIL");auto rt_ct=ct->Clone();inv2(rt_ct);times2(rt_ct);bool ctsame=true;for(size_t e=0;e<ct->GetElements().size();++e){auto a=ct->GetElements()[e];auto b=rt_ct->GetElements()[e];a.SetFormat(Format::COEFFICIENT);b.SetFormat(Format::COEFFICIENT);for(size_t j=0;j<a.GetAllElements().size();++j)for(size_t k=0;k<a.GetAllElements()[j].GetLength();++k)if(a.GetAllElements()[j][k]!=b.GetAllElements()[j][k])ctsame=false;}printf("ciphertext_roundtrip=%s\\n",ctsame?"PASS":"FAIL");auto conj=[&](CT z){return cc->EvalAutomorphism(z,cj,*ck);};show(cc,ct,kp.secretKey,"in");auto y=conj(ct);auto r0=cc->EvalMult(cc->EvalAdd(ct,y),.5);show(cc,r0,kp.secretKey,"scalar_after_add");auto pre=ct->Clone();inv2(pre);auto r1=cc->EvalAdd(pre,conj(pre));show(cc,r1,kp.secretKey,"inv2_before_conj");auto post=cc->EvalAdd(ct,y);inv2(post);show(cc,post,kp.secretKey,"inv2_after_add");auto rt_final=ct->Clone();inv2(rt_final);times2(rt_final);show(cc,rt_final,kp.secretKey,"inv2_times2");return 0;}
